version: '3.7'

services:
  libery_gunicorn:
    container_name: book-web
    volumes:
      - static:/app/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"
  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - static:/app/static
    ports:
      - "80:80"
    depends_on:
      - libery_gunicorn

volumes:
  static: