# Generated by Django 4.0.5 on 2022-06-02 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام نویسنده')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('slug', models.SlugField(unique=True, verbose_name='آدرس')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='نام کتاب')),
                ('slug', models.SlugField(unique=True, verbose_name='آدرس')),
                ('description', models.TextField(verbose_name='توضیحات کتاب')),
                ('photo', models.ImageField(upload_to='images/%Y/%m/%d/', verbose_name='عکس محصول')),
                ('release_date', models.DateField(verbose_name='تاریخ انتشار کتاب')),
                ('reserve', models.BooleanField(default=False, verbose_name='رزرو شده ؟')),
                ('athore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_athore', to='book.author', verbose_name='نویسنده کتاب')),
                ('genre', models.ManyToManyField(related_name='book_genre', to='book.genre', verbose_name='ژانر کتاب')),
            ],
        ),
    ]
