# Generated by Django 4.0.5 on 2022-06-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='release_date',
            field=models.IntegerField(verbose_name='تاریخ انتشار کتاب'),
        ),
    ]
