# Generated by Django 4.0.5 on 2022-06-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.ImageField(upload_to='images/book/%Y/%m/%d/', verbose_name='عکس محصول'),
        ),
    ]
